language: python
#env:
#   global:
#       - secure: "pvQHCsdcIRjwNvsBrZxP8cZWEwug0+PLg1T8841ZLkMdCaO3YheqmxF1xGjAqty6hLppz6vX1LFEKmPjKurLL0/i+be6MhT8/ZikFpSan7TdNUqISxeFx31ls+QpuFKzCV7ZEx7C1ms8LPWEGmzMMN6bCtOBVtGznD9KKWZmLlA="
matrix:
    include:
        - os: linux
          python: 3.5
          env:
            - BUILD_DOCS=true

before_install:
  - URL="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh";
    wget "${URL}" -O miniconda.sh;
    bash miniconda.sh -b -p $HOME/miniconda;
    export PATH="$HOME/miniconda/bin:$PATH";
    hash -r;
    conda config --set always_yes yes --set changeps1 no --add channels conda-forge;
    conda update -q conda;
    conda info -a;

install:
  - conda install doctr regolith

script:
  - regolith build html;

#    doctr deploy --deploy-repo ergs/twofcs.ergs.sc.edu;

